// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOfdmUMXXrU8uwz0UYQALGUjBMKq54bug',
    appId: '1:188603843845:web:18ea3b73ab14a7f7eae36c',
    messagingSenderId: '188603843845',
    projectId: 'onion-quality-grading',
    authDomain: 'onion-quality-grading.firebaseapp.com',
    storageBucket: 'onion-quality-grading.firebasestorage.app',
    measurementId: 'G-56E5Q045CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCheUaajd_F1v3QcJdLG-CuUSaFlMS80jc',
    appId: '1:188603843845:android:efa11730354bc2b8eae36c',
    messagingSenderId: '188603843845',
    projectId: 'onion-quality-grading',
    storageBucket: 'onion-quality-grading.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0gCARr6dyDMu4LvRw2HoA8JqnzEYkTWk',
    appId: '1:188603843845:ios:59958c20c50c7148eae36c',
    messagingSenderId: '188603843845',
    projectId: 'onion-quality-grading',
    storageBucket: 'onion-quality-grading.firebasestorage.app',
    iosClientId: '188603843845-qc9hp60vph8fd5epaf1t7r1a5agnm8oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.billApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0gCARr6dyDMu4LvRw2HoA8JqnzEYkTWk',
    appId: '1:188603843845:ios:59958c20c50c7148eae36c',
    messagingSenderId: '188603843845',
    projectId: 'onion-quality-grading',
    storageBucket: 'onion-quality-grading.firebasestorage.app',
    iosClientId: '188603843845-qc9hp60vph8fd5epaf1t7r1a5agnm8oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.billApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOfdmUMXXrU8uwz0UYQALGUjBMKq54bug',
    appId: '1:188603843845:web:1636edfa976ee40feae36c',
    messagingSenderId: '188603843845',
    projectId: 'onion-quality-grading',
    authDomain: 'onion-quality-grading.firebaseapp.com',
    storageBucket: 'onion-quality-grading.firebasestorage.app',
    measurementId: 'G-42NY6VGM3M',
  );
}
