const Map<String, String> teluguTranslations = {
  'appName': 'ఉల్లి నాణ్యత గ్రేడింగ్',
  'getStarted': 'ప్రారంభించండి',
  'login': 'లాగిన్',
  'logout': 'లాగ్ అవుట్',

  'loginContinue': 'మీ ఉల్లికి గ్రేడింగ్ కొనసాగించడానికి లాగిన్ చేయండి',
  'email': 'ఇమెయిల్',
  'password': 'పాస్‌వర్డ్',
  'username': 'వినియోగదారు పేరు',
  'confirmPassword': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',

  'uploadImage': 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
  'uploadHeapPhotos': 'ఉల్లి కుప్ప ఫోటోలను అప్‌లోడ్ చేయండి',
  'camera': 'కెమెరా',
  'gallery': 'గ్యాలరీ',
  'analyze': 'విశ్లేషించండి',
  'analyzeHeap': 'కుప్పను విశ్లేషించండి',
  'analyzing': 'విశ్లేషిస్తోంది...',

  'results': 'విశ్లేషణ ఫలితాలు',
  'qualityGrade': 'నాణ్యత గ్రేడ్',
  'qualityScore': 'నాణ్యత స్కోర్',
  'healthy': 'ఆరోగ్యకరమైన',
  'unhealthy': 'అనారోగ్యకరమైన',
  'small': 'చిన్నది',
  'medium': 'మధ్యస్థం',
  'large': 'పెద్దది',
  'onionsDetected': 'గుర్తించిన ఉల్లిపాయలు',
  'sizeDistribution': 'పరిమాణ పంపిణీ',

  'estimatedMarketPrice': 'అంచనా మార్కెట్ ధర',
  'perQuintal': 'క్వింటాల్‌కు',

  'marketPrices': 'మార్కెట్ ధరలు',
  'market': 'మార్కెట్',
  'district': 'జిల్లా',
  'state': 'రాష్ట్రం',
  'variety': 'రకం',
  'minimum': 'కనిష్టం',
  'maximum': 'గరిష్టం',
  'modal': 'మోడల్ ధర',
  'arrivalDate': 'రాక తేదీ',

  'generatePdf': 'PDF నివేదికను రూపొందించండి',
  'generatingPdf': 'PDF రూపొందుతోంది...',
  'savingReport': 'నివేదిక సేవ్ అవుతోంది...',

  'excellent': 'అద్భుతమైన నాణ్యత',
  'good': 'మంచి నాణ్యత',
  'average': 'సగటు నాణ్యత',
  'poor': 'తక్కువ నాణ్యత',

  'language': 'భాష',

  'noOnionsDetected': 'ఉల్లిపాయలు ఏవీ గుర్తించబడలేదు',
  'invalidImage': 'చెల్లని చిత్రం',
  'max5Images': 'గరిష్టంగా 5 చిత్రాలు',
  'selectAtLeastOne': 'కనీసం ఒక చిత్రాన్ని ఎంచుకోండి',

  'welcomeBack': 'తిరిగి స్వాగతం! 👋',
  'readyCheckQuality': 'మీ ఉల్లి నాణ్యతను తనిఖీ చేయడానికి సిద్ధంగా ఉన్నారా?',
  'uploadAssessment':
      'ఉల్లి చిత్రాన్ని అప్‌లోడ్ చేసి AI ఆధారిత నాణ్యత అంచనాను పొందండి.',
  'whatWouldYouLike': 'మీరు ఏమి చేయాలనుకుంటున్నారు?',
  'qualityTip': 'నాణ్యత సూచన',
  'qualityTipDescription':
      'మెరుగైన గ్రేడింగ్ ఖచ్చితత్వం కోసం మంచి వెలుతురులో స్పష్టమైన ఉల్లి చిత్రాన్ని అప్‌లోడ్ చేయండి.',
  'smartSimpleReliable': 'స్మార్ట్ • సరళమైనది • నమ్మదగినది',
  'aiPoweredGrading': 'AI ఆధారిత గ్రేడింగ్',
  'onionQuality': 'ఉల్లి నాణ్యత',

  'invalidEmailPassword': 'చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్.',
  'invalidEmail': 'దయచేసి సరైన ఇమెయిల్ చిరునామాను నమోదు చేయండి.',
  'userNotFound': 'ఈ ఇమెయిల్‌తో ఖాతా కనుగొనబడలేదు.',
  'wrongPassword': 'తప్పు పాస్‌వర్డ్.',
  'userDisabled': 'ఈ ఖాతా నిలిపివేయబడింది.',
  'tooManyAttempts': 'చాలా ప్రయత్నాలు జరిగాయి. తర్వాత మళ్లీ ప్రయత్నించండి.',
  'networkError': 'నెట్‌వర్క్ లోపం. మీ ఇంటర్నెట్ కనెక్షన్‌ను తనిఖీ చేయండి.',
  'loginFailed': 'లాగిన్ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
  'enterEmailFirst': 'ముందుగా మీ ఇమెయిల్‌ను నమోదు చేయండి.',
  'passwordResetSent':
      'పాస్‌వర్డ్ రీసెట్ ఇమెయిల్ పంపబడింది. మీ ఇన్‌బాక్స్‌ను తనిఖీ చేయండి.',
  'resetEmailFailed':
      'రీసెట్ ఇమెయిల్ పంపడం సాధ్యపడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
  'enterEmail': 'మీ ఇమెయిల్‌ను నమోదు చేయండి',
  'enterPassword': 'మీ పాస్‌వర్డ్‌ను నమోదు చేయండి',
  'forgotPassword': 'పాస్‌వర్డ్ మర్చిపోయారా?',
  'dontHaveAccount': 'ఖాతా లేదా?',

  'refresh': 'రిఫ్రెష్',
  'onionMandiPrices': 'ఉల్లి మండి ధరలు',
  'latestMarketPrices': 'వివిధ మార్కెట్ల తాజా ధరలు',
  'filterByState': 'రాష్ట్రం ఆధారంగా ఫిల్టర్ చేయండి',
  'allStates': 'అన్ని రాష్ట్రాలు',
  'noMarketPrices': 'మార్కెట్ ధరలు లేవు',
  'noMarketPricesSelectedState':
      'ఎంచుకున్న రాష్ట్రానికి మార్కెట్ ధరలు అందుబాటులో లేవు.',
  'unableToLoadMarketPrices': 'మార్కెట్ ధరలను లోడ్ చేయడం సాధ్యపడలేదు',
  'tryAgain': 'మళ్లీ ప్రయత్నించండి',
  'unknownMarket': 'తెలియని మార్కెట్',
  'perUnit': 'ఒక్కో యూనిట్‌కు',

  'createAccount': 'ఖాతాను సృష్టించండి',
  'createAccountDescription': 'మీ ఉల్లి నాణ్యత గ్రేడింగ్ ఖాతాను సృష్టించండి',
  'enterUsername': 'మీ వినియోగదారు పేరును నమోదు చేయండి',
  'enterUsernameValidation': 'దయచేసి మీ వినియోగదారు పేరును నమోదు చేయండి',
  'usernameMinTwo': 'వినియోగదారు పేరులో కనీసం 2 అక్షరాలు ఉండాలి',
  'enterEmailValidation': 'దయచేసి మీ ఇమెయిల్‌ను నమోదు చేయండి',
  'validEmail': 'దయచేసి సరైన ఇమెయిల్‌ను నమోదు చేయండి',
  'enterPasswordValidation': 'దయచేసి మీ పాస్‌వర్డ్‌ను నమోదు చేయండి',
  'confirmYourPassword': 'మీ పాస్‌వర్డ్‌ను నిర్ధారించండి',
  'confirmPasswordValidation': 'దయచేసి మీ పాస్‌వర్డ్‌ను నిర్ధారించండి',
  'passwordsDoNotMatch': 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
  'alreadyHaveAccount': 'ఇప్పటికే ఖాతా ఉందా?',
  'unableToCreateAccount': 'ఖాతాను సృష్టించడం సాధ్యపడలేదు.',
  'accountCreatedLogin': 'ఖాతా విజయవంతంగా సృష్టించబడింది. దయచేసి లాగిన్ చేయండి.',
  'registrationFailed': 'నమోదు విఫలమైంది.',
  'emailAlreadyRegistered': 'ఈ ఇమెయిల్ ఇప్పటికే నమోదు చేయబడింది.',
  'pleaseEnterValidEmail': 'దయచేసి సరైన ఇమెయిల్ చిరునామాను నమోదు చేయండి.',
  'passwordMinSix': 'పాస్‌వర్డ్‌లో కనీసం 6 అక్షరాలు ఉండాలి.',
  'emailPasswordAuthDisabled':
      'Firebaseలో ఇమెయిల్/పాస్‌వర్డ్ ప్రమాణీకరణ ప్రారంభించబడలేదు.',
  'checkInternet': 'దయచేసి మీ ఇంటర్నెట్ కనెక్షన్‌ను తనిఖీ చేయండి.',
  'databaseError': 'డేటాబేస్ లోపం',
  'unableToSaveUser': 'వినియోగదారు సమాచారాన్ని సేవ్ చేయడం సాధ్యపడలేదు.',
  'somethingWentWrong': 'ఏదో తప్పు జరిగింది',

  'onions': 'ఉల్లిపాయలు',
  'analysisResults': 'విశ్లేషణ ఫలితాలు',
  'unavailable': 'అందుబాటులో లేదు',
  'states': 'రాష్ట్రాలు',
  'markets': 'మార్కెట్లు',
  'generatePdfReport': 'PDF నివేదికను రూపొందించండి',
  'reportSavedSuccessfully': 'నివేదిక విజయవంతంగా సేవ్ చేయబడింది.',
  'reportUploadedSuccessfully': 'నివేదిక విజయవంతంగా అప్‌లోడ్ చేయబడింది.',
  'localFile': 'స్థానిక ఫైల్',
  'pdfGenerationFailed': 'PDF రూపొందించడం విఫలమైంది',
  'analyzeAnotherImage': 'మరొక చిత్రాన్ని విశ్లేషించండి',

  'analyzeYourOnionHeap': 'మీ ఉల్లి కుప్పను విశ్లేషించండి',
  'sameHeapDifferentAngles':
      'అదే కుప్పను వివిధ కోణాల నుండి తీసిన అనేక ఫోటోలను జోడించండి.',
  'photosSelected': 'ఫోటోలు ఎంచుకోబడ్డాయి',
  'tapToRemove': 'తొలగించడానికి × నొక్కండి',
  'noPhotosSelected': 'ఫోటోలు ఏవీ ఎంచుకోలేదు',
  'takePhotoOrChooseGallery':
      'ఫోటో తీయండి లేదా ప్రారంభించడానికి గ్యాలరీ నుండి చిత్రాలను ఎంచుకోండి.',
  'upToFivePhotos': 'ఒక్కో కుప్పకు గరిష్టంగా 5 ఫోటోలు',
  'photo': 'ఫోటో',
  'maximumFivePhotos': 'ఒక్కో కుప్పకు గరిష్టంగా 5 ఫోటోలు మాత్రమే అనుమతించబడతాయి.',
  'onlyFivePhotos': 'ఒక్కో కుప్పకు 5 ఫోటోలు మాత్రమే ఉపయోగించవచ్చు.',
  'addAtLeastOnePhoto': 'దయచేసి కనీసం ఒక కుప్ప ఫోటోను జోడించండి.',

  'onionQualityGrading': 'ఉల్లి నాణ్యత గ్రేడింగ్',
  'smartSimpleDescription':
      'AI సాంకేతికతతో పనిచేసే\nస్మార్ట్ మరియు సరళమైన ఉల్లి నాణ్యత అంచనా.',
  'gradeYourOnionsEasily': 'మీ ఉల్లికి సులభంగా గ్రేడింగ్ చేయండి',
  'uploadImageInstantAssessment':
      'ఉల్లి చిత్రాన్ని అప్‌లోడ్ చేసి తక్షణ నాణ్యత అంచనాను పొందండి.',
  'whyUseOnionQualityGrading':
      'ఉల్లి నాణ్యత గ్రేడింగ్‌ను ఎందుకు ఉపయోగించాలి?',
  'easy': 'సులభం',
  'uploadAnImage': 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
  'smart': 'స్మార్ట్',
  'fast': 'వేగవంతం',
  'instantResults': 'తక్షణ ఫలితాలు',
  'capture': 'క్యాప్చర్',
  'grade': 'గ్రేడ్',
  'smartGradingBetterQuality':
      'స్మార్ట్ గ్రేడింగ్ • మెరుగైన నాణ్యత • మెరుగైన నిర్ణయాలు',
  'gradeYourOnions': 'మీ ఉల్లికి గ్రేడ్ చేయండి',
  'gradeYourOnionsDescription': 'మీ ఉల్లికి సులభంగా గ్రేడింగ్ చేయండి',
};