const Map<String, String> hindiTranslations = {
  'appName': 'प्याज गुणवत्ता ग्रेडिंग',
  'getStarted': 'शुरू करें',
  'login': 'लॉगिन',
  'logout': 'लॉगआउट',

  'loginContinue': 'अपने प्याज की ग्रेडिंग जारी रखने के लिए लॉगिन करें',
  'email': 'ईमेल',
  'password': 'पासवर्ड',
  'username': 'उपयोगकर्ता नाम',
  'confirmPassword': 'पासवर्ड की पुष्टि करें',

  'uploadImage': 'छवि अपलोड करें',
  'uploadHeapPhotos': 'प्याज के ढेर की तस्वीरें अपलोड करें',
  'camera': 'कैमरा',
  'gallery': 'गैलरी',
  'analyze': 'विश्लेषण करें',
  'analyzeHeap': 'ढेर का विश्लेषण करें',
  'analyzing': 'विश्लेषण हो रहा है...',

  'results': 'विश्लेषण परिणाम',
  'qualityGrade': 'गुणवत्ता ग्रेड',
  'qualityScore': 'गुणवत्ता स्कोर',
  'healthy': 'स्वस्थ',
  'unhealthy': 'अस्वस्थ',
  'small': 'छोटा',
  'medium': 'मध्यम',
  'large': 'बड़ा',
  'onionsDetected': 'पहचाने गए प्याज',
  'sizeDistribution': 'आकार वितरण',

  'estimatedMarketPrice': 'अनुमानित बाजार मूल्य',
  'perQuintal': 'प्रति क्विंटल',

  'marketPrices': 'बाजार मूल्य',
  'market': 'बाजार',
  'district': 'जिला',
  'state': 'राज्य',
  'variety': 'किस्म',
  'minimum': 'न्यूनतम',
  'maximum': 'अधिकतम',
  'modal': 'मॉडल',
  'arrivalDate': 'आगमन तिथि',

  'generatePdf': 'PDF रिपोर्ट बनाएं',
  'generatingPdf': 'PDF बनाई जा रही है...',
  'savingReport': 'रिपोर्ट सहेजी जा रही है...',

  'excellent': 'उत्कृष्ट गुणवत्ता',
  'good': 'अच्छी गुणवत्ता',
  'average': 'औसत गुणवत्ता',
  'poor': 'खराब गुणवत्ता',

  'language': 'भाषा',

  'noOnionsDetected': 'कोई प्याज नहीं मिला',
  'invalidImage': 'अमान्य छवि',
  'max5Images': 'अधिकतम 5 छवियां',
  'selectAtLeastOne': 'कम से कम एक छवि चुनें',

  'welcomeBack': 'वापसी पर स्वागत है! 👋',
  'readyCheckQuality': 'क्या आप अपने प्याज की गुणवत्ता जांचने के लिए तैयार हैं?',
  'uploadAssessment':
      'प्याज की छवि अपलोड करें और AI आधारित गुणवत्ता मूल्यांकन प्राप्त करें।',
  'whatWouldYouLike': 'आप क्या करना चाहते हैं?',
  'qualityTip': 'गुणवत्ता सुझाव',
  'qualityTipDescription':
      'बेहतर ग्रेडिंग सटीकता के लिए अच्छी रोशनी में प्याज की स्पष्ट छवि अपलोड करें।',
  'smartSimpleReliable': 'स्मार्ट • सरल • विश्वसनीय',
  'aiPoweredGrading': 'AI आधारित ग्रेडिंग',
  'onionQuality': 'प्याज की गुणवत्ता',

  'invalidEmailPassword': 'गलत ईमेल या पासवर्ड।',
  'invalidEmail': 'कृपया सही ईमेल पता दर्ज करें।',
  'userNotFound': 'इस ईमेल से कोई खाता नहीं मिला।',
  'wrongPassword': 'गलत पासवर्ड।',
  'userDisabled': 'यह खाता अक्षम कर दिया गया है।',
  'tooManyAttempts': 'बहुत अधिक प्रयास किए गए हैं। बाद में पुनः प्रयास करें।',
  'networkError': 'नेटवर्क त्रुटि। अपना इंटरनेट कनेक्शन जांचें।',
  'loginFailed': 'लॉगिन विफल हुआ। कृपया पुनः प्रयास करें।',
  'enterEmailFirst': 'पहले अपना ईमेल दर्ज करें।',
  'passwordResetSent':
      'पासवर्ड रीसेट ईमेल भेज दिया गया है। अपना इनबॉक्स जांचें।',
  'resetEmailFailed':
      'रीसेट ईमेल भेजने में असमर्थ। कृपया पुनः प्रयास करें।',
  'enterEmail': 'अपना ईमेल दर्ज करें',
  'enterPassword': 'अपना पासवर्ड दर्ज करें',
  'forgotPassword': 'पासवर्ड भूल गए?',
  'dontHaveAccount': 'खाता नहीं है?',

  'refresh': 'रीफ्रेश करें',
  'onionMandiPrices': 'प्याज मंडी मूल्य',
  'latestMarketPrices': 'विभिन्न बाजारों के नवीनतम मूल्य',
  'filterByState': 'राज्य के अनुसार फ़िल्टर करें',
  'allStates': 'सभी राज्य',
  'noMarketPrices': 'कोई बाजार मूल्य नहीं',
  'noMarketPricesSelectedState':
      'चयनित राज्य के लिए कोई बाजार मूल्य उपलब्ध नहीं है।',
  'unableToLoadMarketPrices': 'बाजार मूल्य लोड करने में असमर्थ',
  'tryAgain': 'पुनः प्रयास करें',
  'unknownMarket': 'अज्ञात बाजार',
  'perUnit': 'प्रति इकाई',

  'createAccount': 'खाता बनाएं',
  'createAccountDescription': 'अपना प्याज गुणवत्ता ग्रेडिंग खाता बनाएं',
  'enterUsername': 'अपना उपयोगकर्ता नाम दर्ज करें',
  'enterUsernameValidation': 'कृपया अपना उपयोगकर्ता नाम दर्ज करें',
  'usernameMinTwo': 'उपयोगकर्ता नाम में कम से कम 2 अक्षर होने चाहिए',
  'enterEmailValidation': 'कृपया अपना ईमेल दर्ज करें',
  'validEmail': 'कृपया सही ईमेल दर्ज करें',
  'enterPasswordValidation': 'कृपया अपना पासवर्ड दर्ज करें',
  'confirmYourPassword': 'अपने पासवर्ड की पुष्टि करें',
  'confirmPasswordValidation': 'कृपया अपने पासवर्ड की पुष्टि करें',
  'passwordsDoNotMatch': 'पासवर्ड मेल नहीं खाते',
  'alreadyHaveAccount': 'पहले से खाता है?',
  'unableToCreateAccount': 'खाता बनाने में असमर्थ।',
  'accountCreatedLogin': 'खाता सफलतापूर्वक बनाया गया। कृपया लॉगिन करें।',
  'registrationFailed': 'पंजीकरण विफल हुआ।',
  'emailAlreadyRegistered': 'यह ईमेल पहले से पंजीकृत है।',
  'pleaseEnterValidEmail': 'कृपया सही ईमेल पता दर्ज करें।',
  'passwordMinSix': 'पासवर्ड में कम से कम 6 अक्षर होने चाहिए।',
  'emailPasswordAuthDisabled':
      'Firebase में ईमेल/पासवर्ड प्रमाणीकरण सक्षम नहीं है।',
  'checkInternet': 'कृपया अपना इंटरनेट कनेक्शन जांचें।',
  'databaseError': 'डेटाबेस त्रुटि',
  'unableToSaveUser': 'उपयोगकर्ता की जानकारी सहेजने में असमर्थ।',
  'somethingWentWrong': 'कुछ गलत हो गया',

  'onions': 'प्याज',
  'analysisResults': 'विश्लेषण परिणाम',
  'unavailable': 'उपलब्ध नहीं',
  'states': 'राज्य',
  'markets': 'बाजार',
  'generatePdfReport': 'PDF रिपोर्ट बनाएं',
  'reportSavedSuccessfully': 'रिपोर्ट सफलतापूर्वक सहेजी गई।',
  'reportUploadedSuccessfully': 'रिपोर्ट सफलतापूर्वक अपलोड की गई।',
  'localFile': 'स्थानीय फ़ाइल',
  'pdfGenerationFailed': 'PDF बनाना विफल हुआ',
  'analyzeAnotherImage': 'एक और छवि का विश्लेषण करें',

  'analyzeYourOnionHeap': 'अपने प्याज के ढेर का विश्लेषण करें',
  'sameHeapDifferentAngles':
      'एक ही ढेर की अलग-अलग कोणों से कई तस्वीरें जोड़ें।',
  'photosSelected': 'तस्वीरें चुनी गईं',
  'tapToRemove': 'हटाने के लिए × दबाएं',
  'noPhotosSelected': 'कोई तस्वीर नहीं चुनी गई',
  'takePhotoOrChooseGallery':
      'फोटो लें या शुरू करने के लिए गैलरी से तस्वीरें चुनें।',
  'upToFivePhotos': 'प्रति ढेर अधिकतम 5 तस्वीरें',
  'photo': 'फोटो',
  'maximumFivePhotos': 'एक ढेर के लिए अधिकतम 5 तस्वीरों की अनुमति है।',
  'onlyFivePhotos': 'एक ढेर के लिए केवल 5 तस्वीरों का उपयोग किया जा सकता है।',
  'addAtLeastOnePhoto': 'कृपया कम से कम एक ढेर की तस्वीर जोड़ें।',

  'onionQualityGrading': 'प्याज गुणवत्ता ग्रेडिंग',
  'smartSimpleDescription':
      'AI तकनीक द्वारा संचालित\nस्मार्ट और सरल प्याज गुणवत्ता मूल्यांकन।',
  'gradeYourOnionsEasily': 'अपने प्याज की आसानी से ग्रेडिंग करें',
  'uploadImageInstantAssessment':
      'प्याज की छवि अपलोड करें और तुरंत गुणवत्ता मूल्यांकन प्राप्त करें।',
  'whyUseOnionQualityGrading':
      'प्याज गुणवत्ता ग्रेडिंग का उपयोग क्यों करें?',
  'easy': 'आसान',
  'uploadAnImage': 'एक छवि अपलोड करें',
  'smart': 'स्मार्ट',
  'fast': 'तेज़',
  'instantResults': 'तुरंत परिणाम',
  'capture': 'कैप्चर',
  'grade': 'ग्रेड',
  'smartGradingBetterQuality':
      'स्मार्ट ग्रेडिंग • बेहतर गुणवत्ता • बेहतर निर्णय',
};