from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from datetime import datetime


def generate_pdf(result, output_path):

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=22,
        alignment=TA_CENTER,
        spaceAfter=8,
    )

    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        parent=styles["Normal"],
        fontSize=10,
        alignment=TA_CENTER,
        textColor=colors.grey,
        spaceAfter=18,
    )

    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading2"],
        fontSize=14,
        spaceBefore=12,
        spaceAfter=8,
    )

    normal_style = ParagraphStyle(
        "NormalStyle",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
    )

    story = []

    # ---------------------------------------------------------
    # TITLE
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "ONION QUALITY GRADING REPORT",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "AI-Powered Onion Quality Analysis",
            subtitle_style,
        )
    )

    # ---------------------------------------------------------
    # REPORT INFORMATION
    # ---------------------------------------------------------

    current_time = datetime.now().strftime(
        "%d-%m-%Y %H:%M:%S"
    )

    generated_by = result.get(
        "username",
        "Unknown User"
    )

    story.append(
        Paragraph(
            f"<b>Generated By:</b> {generated_by}",
            normal_style,
        )
    )

    story.append(
        Paragraph(
            f"<b>Analysis Date &amp; Time:</b> {current_time}",
            normal_style,
        )
    )

    story.append(Spacer(1, 10))

    # ---------------------------------------------------------
    # QUALITY RESULT
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "Quality Assessment",
            heading_style,
        )
    )

    grade = result.get("grade", "N/A")
    description = result.get("description", "N/A")
    final_score = result.get("final_score", 0)

    quality_data = [
        ["Parameter", "Result"],
        ["Quality Grade", grade],
        ["Quality Score", f"{final_score}/100"],
        ["Description", description],
    ]

    quality_table = Table(
        quality_data,
        colWidths=[55 * mm, 115 * mm],
    )

    quality_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.green,
            ),
            (
                "TEXTCOLOR",
                (0, 0),
                (-1, 0),
                colors.white,
            ),
            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold",
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.grey,
            ),
            (
                "PADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    story.append(quality_table)

    # ---------------------------------------------------------
    # ONION COUNT
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "Onion Detection & Classification",
            heading_style,
        )
    )

    count_data = [
        ["Category", "Count"],
        ["Total Onions", result.get("total_onions", 0)],
        ["Healthy", result.get("healthy", 0)],
        ["Unhealthy", result.get("unhealthy", 0)],
        ["Small", result.get("small", 0)],
        ["Medium", result.get("medium", 0)],
        ["Large", result.get("large", 0)],
    ]

    count_table = Table(
        count_data,
        colWidths=[100 * mm, 70 * mm],
    )

    count_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.green,
            ),
            (
                "TEXTCOLOR",
                (0, 0),
                (-1, 0),
                colors.white,
            ),
            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold",
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.grey,
            ),
            (
                "PADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    story.append(count_table)

    # ---------------------------------------------------------
    # SCORES
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "Quality Scores",
            heading_style,
        )
    )

    score_data = [
        ["Score", "Value"],
        [
            "Health Score",
            f"{result.get('health_score', 0)}/100",
        ],
        [
            "Size Score",
            f"{result.get('size_score', 0)}/100",
        ],
        [
            "Final Score",
            f"{result.get('final_score', 0)}/100",
        ],
    ]

    score_table = Table(
        score_data,
        colWidths=[100 * mm, 70 * mm],
    )

    score_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.green,
            ),
            (
                "TEXTCOLOR",
                (0, 0),
                (-1, 0),
                colors.white,
            ),
            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold",
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.grey,
            ),
            (
                "PADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    story.append(score_table)

    # ---------------------------------------------------------
    # MARKET PRICE
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "Mandi Price Intelligence",
            heading_style,
        )
    )

    estimated_price = result.get(
        "estimated_price"
    )

    price_basis = result.get(
        "price_basis",
        "N/A"
    )

    market = result.get("market")

    if market:

        market_data = [
            ["Market Parameter", "Value"],
            [
                "Markets Covered",
                market.get("markets", 0),
            ],
            [
                "States Covered",
                market.get("states", 0),
            ],
            [
                "Records Used",
                market.get("records", 0),
            ],
            [
                "Average Minimum",
                f"₹{market.get('average_min_price', 0)}",
            ],
            [
                "Average Modal",
                f"₹{market.get('average_modal_price', 0)}",
            ],
            [
                "Average Maximum",
                f"₹{market.get('average_max_price', 0)}",
            ],
        ]

        market_table = Table(
            market_data,
            colWidths=[100 * mm, 70 * mm],
        )

        market_table.setStyle(
            TableStyle([
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.green,
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey,
                ),
                (
                    "PADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
            ])
        )

        story.append(market_table)

        story.append(Spacer(1, 10))

    if estimated_price is not None:

        story.append(
            Paragraph(
                f"<b>Estimated Price:</b> "
                f"₹{estimated_price} per quintal",
                normal_style,
            )
        )

        story.append(
            Paragraph(
                f"<b>Price Basis:</b> {price_basis}",
                normal_style,
            )
        )

    # ---------------------------------------------------------
    # INDIVIDUAL ONION RESULTS
    # ---------------------------------------------------------

    onions = result.get("onions", [])

    if onions:

        story.append(
            Paragraph(
                "Individual Onion Analysis",
                heading_style,
            )
        )

        onion_data = [
            [
                "No.",
                "Health",
                "Size",
                "Diameter (px)",
            ]
        ]

        for index, onion in enumerate(
            onions,
            start=1
        ):
            onion_data.append([
                index,
                onion.get("health", "N/A"),
                onion.get("size", "N/A"),
                onion.get("diameter", "N/A"),
            ])

        onion_table = Table(
            onion_data,
            colWidths=[
                15 * mm,
                45 * mm,
                45 * mm,
                45 * mm,
            ],
            repeatRows=1,
        )

        onion_table.setStyle(
            TableStyle([
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.green,
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey,
                ),
                (
                    "PADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "FONTSIZE",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
            ])
        )

        story.append(onion_table)

    # ---------------------------------------------------------
    # FOOTER
    # ---------------------------------------------------------

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by Onion Quality Grading System",
            subtitle_style,
        )
    )

    doc.build(story)